version: "2"
services:
  web:
    build:
      context: ./.
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "4848:4848"
    links:
      - dbpostgres
    volumes:
      - ".:/var/www/html"
  dbpostgres:
    image: postgres:latest
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: ratemydoctor